#
#/// \dir AppKillSpin/Executables
#/// General operators for initial value problem for black holes

CODE_HOME = ../..

SUBDIRECTORIES = 

FACTORY_LIBS = \
#    AmrDrivers \
#    DualFrameItems \
#    DualFrameSystem \
#    EllipticStateChangers \
#    EventTriggers \
#    Evolution \
#    EvolutionObservers \
#    EvolutionStateChangers \
#    FoshAlgorithms \
#    FoshBoundaryConditions \
#    FoshSystem \
#    GeneralizedHarmonic \
#    ImexFoshAlgorithms \
#    ImexGh \
#    ImexScalarWaveCurved \
#    ImexTimeSteppers \
#    TimeSteppers \
#    WaveEquationSolutions \
#    EquationOfState \
#    FIDElliptic \
#    FIDHydro \
#    FiniteDifference \
#    HydroComputeItems \
#    HydroStates \
#    InitialValueProblem \
#    LinearizedGravity \
#    SurfaceFitting \
#    NullInfComputeItems \
#    NullInfinity \
#    StrahlkorperFinderAlgorithm \
#    StrahlkorperItems \
#    StrahlkorperResidual \
#    MinimizationAlgorithm \
#    SpatialCoordMaps \
#    Surface \
    SurfaceFinderItems \
#    BackgroundMetrics \
#    BoundaryConditions \
    ComputeItems \
#    CoordMap \
#    CoordinateTransformations \
    DataBox \
    Domain \
#    EinsteinSolutions \
#    EllipticResidual \
#    EllipticSolver \
#    Functionals \
#    GrItems \
    IO \
#    IndexMap \
#    Interpolators \
#    Math \
#    Observers \
#    Preconditioning \
#    Slice \
#    SpectralFilters \
#    SpectralFunctionals \
#    Subdomain \
#    TensorFunctions \
#    Topology \
#    VolumeTerms \
    AppKillSpin #SpherePackhohejd8 \
    $(NULL)

EXECUTABLES = SpellsAKS #TestSurfaceBasisExt #TestVectorHA  TestGslMultiroots

##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules
