CODE_HOME = ../..

FACTORY_LIBS = \
    ComputeItems \
    AppKillSpin \
    $(NULL)

EXECUTABLES = \
    TestComputeAKV \
    $(NULL)


##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules
